# Generated by Django 4.2.13 on 2024-05-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date2',
        ),
    ]
